name: NARS Lab
description: Network science and machine learning for accessible, resilient and sustainable communities.
url: https://narslab.org

destination: docs
markdown: kramdown
permalink: /:categories/:title/
future: true

plugins:
  - jekyll-twitter-plugin
  - jekyll-include-cache

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
  - "projects/covid-analysis/results/*"
  - "projects/covid-analysis/NYT/*"
  - "projects/covid-analysis/mobility/*"
  - "projects/covid-analysis/rscripts/*"
  - "projects/covid-analysis/.ipynb_checkpoints/*"
  - "projects/covid-analysis/da*"
  - "projects/covid-analysis/c*"
  - "projects/covid-analysis/mobility/*"
  - "projects/tree-risk-ai/figures/*"
  - "projects/tree-risk-ai/data/*"
  - "projects/tree-risk-ai/results/*"
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/

readmes:
  - narslab/tree-risk-ai
  - narslab/equi-resnet

projects:
  # - narslab/tree-risk-ai
  # - narslab/bus-transit-energy
  # - narslab/equi-resnet
  # - narslab/mbta-rail-system-energy
  # - narslab/msa-emission-typologies
  # - narslab/project-groundwork
  # - narslab/pv-trips-energy
  # - narslab/pvta-odx  
  # - narslab/pvta-spatiotemporal-typologies
  # - narslab/tracking-msa-ghg
  # - narslab/treem
  # - narslab/treem-ml-line-energy
  # - narslab/treem-ts-energy-forecast

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
